"use client";

import { useState } from "react";
import { Plus, Minus } from "lucide-react";
import { SectionHeading } from "./SectionHeading";
import { cn } from "@/lib/utils";

const FAQS = [
  {
    q: "What is a MESH Score?",
    a: "A 0–1000 weighted inverse-risk composite. Higher is safer: 900+ is AAA (Verified Safe), below 300 is C (Danger). It's generated by the AI analysis pipeline and attested onchain via EAS on Base.",
  },
  {
    q: "Do I need a wallet or an account?",
    a: "No. The first 5 contract scans and 5 wallet scans each month are free per IP — no signup. A wallet is only needed once you exceed the free quota or want Pro/Enterprise features.",
  },
  {
    q: "What does “EAS-attested” mean?",
    a: "Every scan result is written onchain as an Ethereum Attestation Service attestation on Base. The score and report hash are permanent and independently verifiable — anyone (or any agent) can read the latest MESH Score for an address straight from the registry.",
  },
  {
    q: "How do AI agents use Meshline?",
    a: "Every endpoint is gated with x402 on Base. An agent calls the API, gets a 402, pays 0.001 USDC, and retries — receiving structured JSON. No API key, no account. It's the first onchain risk oracle agents can query before executing a transaction.",
  },
  {
    q: "Is the report shareable?",
    a: "Yes. Every scan generates a permanent public page at meshline.tech/scan/{uid} plus an embeddable trust badge that auto-updates from the latest EAS attestation.",
  },
  {
    q: "What can I scan?",
    a: "Any Base contract address, any Base wallet address, or any Base app URL. Meshline auto-detects the target type and runs the matching pipeline.",
  },
];

function Item({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border-b border-white/10">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="group flex w-full items-center justify-between gap-4 py-5 text-left"
      >
        <span className="text-sm font-bold text-white transition-colors group-hover:text-accent sm:text-base">
          {q}
        </span>
        <span className="shrink-0 text-cyan-brand transition-transform duration-300 group-hover:scale-110">
          {open ? <Minus size={18} /> : <Plus size={18} />}
        </span>
      </button>
      <div
        className={cn(
          "grid transition-all duration-300",
          open ? "grid-rows-[1fr] pb-5 opacity-100" : "grid-rows-[0fr] opacity-0",
        )}
      >
        <p className="overflow-hidden text-sm leading-relaxed text-muted">{a}</p>
      </div>
    </div>
  );
}

export function FAQ() {
  return (
    <section id="faq" className="relative z-10 border-b border-white/10 py-20 sm:py-24">
      <div className="container-mesh max-w-3xl">
        <SectionHeading index="06" eyebrow="FAQ" title="Questions, answered." />
        <div className="mt-10 sm:mt-12">
          {FAQS.map((f) => (
            <Item key={f.q} {...f} />
          ))}
        </div>
      </div>
    </section>
  );
}
